# .github/workflows/release.yml
name: Release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Build and Test
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test       # Optional. Enable if you have tests
      
  get_semver:
    name: Get Valid SemVer
    runs-on: ubuntu-latest
    steps:
      - name: Semver Release
        id: semver_release
        uses: K-Phoen/semver-release-action@v1.3.2
        with:
          release_branch: prod
          release_strategy: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: echo ${{ steps.semver_release.outputs.tag }}
      - run: exit 0

  # push_to_dockerhub:
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3
      
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
      
  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action
  #       with:
  #         images: my-docker-hub-namespace/my-docker-hub-repository
      
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
      