name: Build, Publish and Deploy to GKE

on:
    push:
        branches:
            - main

env:
    GCP_PROJECT_ID: 'tf-gha-k8s-gcp-test-lab'
    GCP_PROJECT_NUMBER: '278154893338'
    GAR_LOCATION: us-central1
    GAR_REPOSITORY: apps
    #TF_STATE_BUCKET_NAME: ''
    IMAGE_NAME: 'hello-app'

jobs:
    deploy:
        runs-on: ubuntu-latest
        env: 
            IMAGE_TAG: ${{ github.sha }}
        permissions: 
            contents: 'read'
            id-token: 'write'
        steps:
            - name: Checkout Repo
              uses: 'actions/checkout@v4'
            
            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v1'
              with:
                credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

            - name: Setup Google Cloud
              uses: 'google-github-actions/setup-gcloud@v1'

            - name: Docker Registry Auth
              run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev --quiet

            # - name: Build and Push Docker Image
            #   run: |
            #     docker build -t us.gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG .
            #     docker push us.gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
            #   working-directory: ./app


            - name: Build Docker Image
              run: |-
                docker build \
                  --tag "$GAR_LOCATION-docker.pkg.dev/$GCP_PROJECT_ID/$GAR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG" \
                  .
              working-directory: ./app
                  
            # Push the Docker image to Google Artifact Registry
            - name: Push Docker Image
              run: |-
                docker push "$GAR_LOCATION-docker.pkg.dev/$GCP_PROJECT_ID/$GAR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG"
              working-directory: ./app

            - name: Setup Terraform
              uses: 'hashicorp/setup-terraform@v2'
            
            - name: Terraform init
              run: terraform init # TODO: change this to use Makefilew with Infisical for prod env
              working-directory: ./terraform

            - name: Terraform Plan
              run: |
                terraform plan \
                -var="container_image=us.gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG"
                -out=PLAN
              # TODO: change this to use Makefilew with Infisical for prod env
              # TODO: Change Terraform files to use variables instead of hard coded values

            - name: Terraform Apply
              run: terraform apply PLAN
