# .github/workflows/release.yml
name: Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Create Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  echo-out:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Echo Tag
        run: echo ${{ needs.release.outputs.tag }}